### ISSUE TITLE
aggregator send kmers to customers

### ISSUE THREAD

**Issue by sebhtml** [GeneAssembly/biosal#213]

**Comment by sebhtml** [comment]
#0  0x0000000000411728 in bsal_dna_sequence_init (sequence=0x0, data=0x7f2b88784330) at data/dna_sequence.c:23
#1  0x0000000000411991 in bsal_dna_sequence_init_copy (self=0x0, other=0x7f2b8881f180) at data/dna_sequence.c:149
#2  0x000000000040a5b9 in bsal_sequence_store_store_sequences (actor=0x7f2bb0e38cb8, message=0x23c6c80) at storage/sequence_store.c:168
#3  0x000000000040a430 in bsal_sequence_store_receive (actor=0x7f2bb0e38cb8, message=0x23c6c80) at storage/sequence_store.c:69
#4  0x0000000000404c24 in bsal_actor_receive (actor=0x7f2bb0e38cb8, message=0x23c6c80) at engine/actor.c:816
#5  0x0000000000406320 in bsal_worker_work (worker=0x23bb710, work=0x7f2bb0635a60) at engine/worker.c:117
#6  0x0000000000406273 in bsal_worker_run (worker=0x23bb710) at engine/worker.c:71
#7  0x00000000004064c9 in bsal_worker_main (worker1=0x23bb710) at engine/worker.c:240
#8  0x00007f2bdb09fe9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f2bdadccccd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000000 in ?? ()

**Comment by sebhtml** [comment]
@hubot says: implemented in commit https://github.com/sebhtml/biosal/commit/6122f7f37cc61c815bc0003536413b234b21ff1f by @sebhtml !
